### PR TITLE
Mod 1.4

### PR DESCRIPTION
**Pull request by biswanathdutta**
Please provide your feedback.

### CODE REVIEW

**Comment by jonquet** [comment]
For the dct:Creator > dc:creator changes... I recall we decided to stay within dct and not dc. What's the motivartion betweem this change ? Harmonization ... I would have change all dc to dct as discussed.

**Comment by biswanathdutta** [comment]
> For the dct:Creator > dc:creator changes... I recall we decided to stay within dct and not dc. What's the motivartion betweem this change ? Harmonization ... I would have change all dc to dct as discussed.
> 
> Note that I don't understand why we still have other dc properties also (title, contributor, etc).... I thought we were supposed to have only dct everywhere.

Moved back to dct.

**Comment by biswanathdutta** [comment]
> .

**Comment by biswanathdutta** [comment]
On Wed, Nov 7, 2018 at 1:28 PM Clement Jonquet <notifications@github.com>
wrote:

> *@jonquet* commented on this pull request.
>
> Another general comment: maybe we could move to Turtle as the default
> syntax... I think we are the only last 2 to work with XML/RDF ;)
>
If you agree, we can go for Turtle.
This will make our life easier.

**Comment by biswanathdutta** [comment]
On Wed 7 Nov, 2018, 1:24 PM Clement Jonquet <notifications@github.com wrote:

> *@jonquet* commented on this pull request.
>
> Thinking about it more and looking at what have been done by the DC folks,
> I would suggest we change our pav:derivedFrom to rdfs:isDefinedBy and we
> provide the versionIRI of MOD in which a property as been imported.
> Check out the defintions of properties inside DC:
> http://dublincore.org/2012/06/14/dcelements#description
> They use: dcterms:description, dcterms:hasVersion, dcterms:issued,
> dcterms:modified, rdfs:comment, rdfs:isDefinedBy, rdfs:label, skos:note
> to describe their properties
>
Yes, I agree, in fact, initially we used rdfs:isDefinedBy for the stated
purpose.

So, if you agree, I can change it back to rdfs: isDefinedBy. And the values
will be the URIs.

Another thing, see DC folks used rdfs:comment to capture the resource
definition.
They used dcterms:description only to capture the additional descriptions
of the resource.

**Comment by biswanathdutta** [comment]
On Wed 7 Nov, 2018, 1:16 PM Clement Jonquet <notifications@github.com wrote:

> *@jonquet* commented on this pull request.
>
> Line 26: Don't are supposed to have a comlete description of MOD
> owl:Ontology object with MOD1.4 properties ? Or at least a maximum number
> of them ?
>
Yes, agree.
Will update.
Also, need to update the MOD description itself.
So far, did not look at it carefully.
Tomorrow, discuss on this.

**Pull request closed without merging**
